language: groovy
jdk:
  - oraclejdk7
branches:
  only:
    - master
script:
  - cd ./spring-auto-scanning && ./grailsw refresh-dependencies && ./grailsw test-app
  - cd ../cucumber && ./grailsw refresh-dependencies && ./grailsw test-app
